/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FunnelsRouteImport } from './routes/funnels'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiIndexRouteImport } from './routes/api.index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelsRoute = FunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/funnels': typeof FunnelsRoute
  '/journey': typeof JourneyRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/': typeof ApiIndexRoute
  '/api/public/events': typeof ApiPublicEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/funnels': typeof FunnelsRoute
  '/journey': typeof JourneyRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api': typeof ApiIndexRoute
  '/api/public/events': typeof ApiPublicEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/funnels': typeof FunnelsRoute
  '/journey': typeof JourneyRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/': typeof ApiIndexRoute
  '/api/public/events': typeof ApiPublicEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/funnels'
    | '/journey'
    | '/sales'
    | '/settings'
    | '/api/events'
    | '/api/'
    | '/api/public/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/funnels'
    | '/journey'
    | '/sales'
    | '/settings'
    | '/api/events'
    | '/api'
    | '/api/public/events'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/funnels'
    | '/journey'
    | '/sales'
    | '/settings'
    | '/api/events'
    | '/api/'
    | '/api/public/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  FunnelsRoute: typeof FunnelsRoute
  JourneyRoute: typeof JourneyRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiIndexRoute: typeof ApiIndexRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnels': {
      id: '/funnels'
      path: '/funnels'
      fullPath: '/funnels'
      preLoaderRoute: typeof FunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  FunnelsRoute: FunnelsRoute,
  JourneyRoute: JourneyRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiIndexRoute: ApiIndexRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
